spring:
  application:
    name: present

server:
  port: 8081

ribbon:
  eureka:
    enabled: false

# az toto zabranilo zobrazovaniu chyby:
# com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
# pri testoch disablnem
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
